---
os: linux
dist: bionic
language: python
python: "3.7"

install:
  # Install Ansible
  - pip3 install ansible

  # Install Ansible Lint
  - pip3 install ansible-lint

  # Check Ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' > ansible.cfg

script:
  # Ansible Lint
  - ansible-lint .
  # Basic role syntax check
  - ansible-playbook tests/test.yaml -i tests/inventory --syntax-check
  # Install NATS and start its service
  - ansible-playbook tests/test.yaml -i tests/inventory --become
  # NATS server version
  - /usr/local/bin/nats-streaming-server -v

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
