---
- name: Install NATS Streaming package from the GitHub.
  apt:
    state: present
    deb: "https://github.com/nats-io/nats-streaming-server/releases/download/\
    v{{ nats_streaming_version }}/\
    nats-streaming-server-v{{ nats_streaming_version }}-amd64.deb"

- name: Create a directory for NATS Streaming
  file:
    path: /var/lib/nats-streaming
    state: directory
    mode: '0755'

- name: Ensure NATS Streaming service file is available.
  template:
    src: nats-streaming-server.service.j2
    dest: /etc/systemd/system/nats-streaming-server.service
    mode: 0644
    backup: true
  notify:
    - reload daemon nats-streaming-server

- name: Ensure NATS Streaming service is started and enabled on boot.
  service:
    name: nats-streaming-server
    state: started
    enabled: true

- name: Create or update NATS Streaming configuration file (/etc/nats-streaming-server.conf)
  template:
    src: nats-streaming-server.conf.j2
    dest: /etc/nats-streaming-server.conf
    mode: 0644
    backup: true
  notify:
    - restart nats-streaming-server
