---
- name: restart nats-streaming-server
  service:
    name: nats-streaming-server
    state: restarted

- name: reload nats-streaming-server
  service:
    name: nats-streaming-server
    state: reloaded

- name: reload daemon nats-streaming-server
  systemd:
    state: stopped
    daemon_reload: true
    name: "nats-streaming-server"

- name: reload daemon nats-exporter
  systemd:
    state: stopped
    daemon_reload: true
    name: "nats-exporter"
